import { Bell, Check, FileText, X } from "lucide-react";
import { useState, type ReactNode } from "react";

import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Drawer } from "@/components/ui/drawer";
import { IconButton } from "@/components/ui/primitives";
import { cn } from "@/lib/utils";

export function AlertDialog({ open, onOpenChange, title, description, confirmLabel = "Confirmer", cancelLabel = "Annuler", destructive, onConfirm }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; confirmLabel?: string; cancelLabel?: string; destructive?: boolean; onConfirm: () => void }) { return <Dialog open={open} onOpenChange={onOpenChange} title={title} description={description}><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" onClick={() => onOpenChange(false)}>{cancelLabel}</Button><Button variant={destructive ? "destructive" : "default"} onClick={() => { onConfirm(); onOpenChange(false); }}>{confirmLabel}</Button></div></Dialog>; }

export function Tag({ children, onRemove, selected, disabled }: { children: ReactNode; onRemove?: () => void; selected?: boolean; disabled?: boolean }) { return <span className={cn("tag", selected && "selected", disabled && "disabled")}>{selected ? <Check aria-hidden="true" /> : null}<span>{children}</span>{onRemove ? <button type="button" disabled={disabled} onClick={onRemove} aria-label={`Retirer ${String(children)}`}><X /></button> : null}</span>; }

export type NotificationItem = { id: string; title: string; description?: string; time?: string; unread?: boolean; href?: string };
export function NotificationCenter({ notifications, onRead, title = "Notifications" }: { notifications: NotificationItem[]; onRead?: (id: string) => void; title?: string }) { const [open, setOpen] = useState(false); const unread = notifications.filter((item) => item.unread).length; return <><button type="button" className="notification-trigger" aria-label={`${title}, ${unread} non lues`} onClick={() => setOpen(true)}><Bell />{unread ? <span>{unread > 9 ? "9+" : unread}</span> : null}</button><Drawer open={open} onOpenChange={setOpen} title={title} description={unread ? `${unread} notification${unread > 1 ? "s" : ""} non lue${unread > 1 ? "s" : ""}` : "Vous êtes à jour"}>{notifications.length ? <div className="notification-list">{notifications.map((item) => <a key={item.id} href={item.href} className={cn(item.unread && "unread")} onClick={() => onRead?.(item.id)}><i aria-hidden="true" /><span><strong>{item.title}</strong>{item.description ? <small>{item.description}</small> : null}{item.time ? <time>{item.time}</time> : null}</span></a>)}</div> : <div className="notification-empty"><Bell /><strong>Aucune notification</strong><p>Les mises à jour de vos démarches apparaîtront ici.</p></div>}</Drawer></>; }

export function FilePreview({ name, size, type, status = "ready", onRemove, onOpen }: { name: string; size?: string; type?: string; status?: "uploading" | "ready" | "error"; onRemove?: () => void; onOpen?: () => void }) { return <div className={cn("file-preview", status)}><span><FileText /></span><button type="button" onClick={onOpen} disabled={!onOpen}><strong>{name}</strong><small>{[type, size].filter(Boolean).join(" · ")}{status === "uploading" ? " · Téléversement…" : status === "error" ? " · Échec du téléversement" : ""}</small></button>{onRemove ? <IconButton size="sm" label={`Retirer ${name}`} onClick={onRemove}><X /></IconButton> : null}</div>; }
