import { Check, ChevronDown, X } from "lucide-react";
import { useEffect, useId, useRef, useState, type KeyboardEvent } from "react";

import { Input } from "@/components/ui/input";

export type MultiSelectOption = { value: string; label: string; description?: string; disabled?: boolean };
export type MultiSelectProps = { label: string; options: MultiSelectOption[]; value: string[]; onValueChange: (value: string[]) => void; placeholder?: string; searchPlaceholder?: string; emptyText?: string; error?: string; hint?: string; disabled?: boolean };
export function MultiSelect({ label, options, value, onValueChange, placeholder = "Sélectionner", searchPlaceholder = "Rechercher…", emptyText = "Aucun résultat", error, hint, disabled }: MultiSelectProps) {
  const id = useId(); const listId = useId(); const messageId = useId(); const rootRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [active, setActive] = useState(0);
  const results = options.filter((option) => `${option.label} ${option.description ?? ""}`.toLocaleLowerCase("fr").includes(query.toLocaleLowerCase("fr")));
  useEffect(() => { if (!open) return; const close = (event: PointerEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, [open]);
  function toggle(option: MultiSelectOption) { if (option.disabled) return; onValueChange(value.includes(option.value) ? value.filter((item) => item !== option.value) : [...value, option.value]); }
  function handleKeyDown(event: KeyboardEvent<HTMLInputElement>) { if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActive((current) => Math.min(current + 1, Math.max(0, results.length - 1))); } else if (event.key === "ArrowUp") { event.preventDefault(); setActive((current) => Math.max(0, current - 1)); } else if (event.key === "Enter" && open) { event.preventDefault(); const option = results[active]; if (option) toggle(option); } else if (event.key === "Escape") setOpen(false); else if (event.key === "Backspace" && !query && value.length) onValueChange(value.slice(0, -1)); }
  return <div className="multi-select field" ref={rootRef}><div className="field-label-row"><label id={id}>{label}</label></div><div className="multi-select-control" aria-labelledby={id} aria-describedby={error || hint ? messageId : undefined} aria-invalid={error ? true : undefined}>{value.map((selected) => { const option = options.find((item) => item.value === selected); return option ? <span className="multi-select-tag" key={selected}>{option.label}<button type="button" onClick={() => toggle(option)} aria-label={`Retirer ${option.label}`} disabled={disabled}><X aria-hidden="true" /></button></span> : null; })}<input role="combobox" aria-label={label} aria-expanded={open} aria-controls={open ? listId : undefined} aria-autocomplete="list" aria-activedescendant={open && results[active] ? `${listId}-${active}` : undefined} disabled={disabled} value={query} placeholder={value.length ? searchPlaceholder : placeholder} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); setActive(0); }} onKeyDown={handleKeyDown} /><ChevronDown aria-hidden="true" /></div>{open ? <div className="multi-select-list" id={listId} role="listbox" aria-multiselectable="true" aria-label={`Options pour ${label}`}>{results.length ? results.map((option, index) => <button type="button" role="option" id={`${listId}-${index}`} aria-selected={value.includes(option.value)} aria-disabled={option.disabled || undefined} key={option.value} onMouseEnter={() => setActive(index)} onClick={() => toggle(option)}><span><strong>{option.label}</strong>{option.description ? <small>{option.description}</small> : null}</span>{value.includes(option.value) ? <Check aria-hidden="true" /> : null}</button>) : <p>{emptyText}</p>}</div> : null}{error ? <p className="field-message error" role="alert" id={messageId}>{error}</p> : hint ? <p className="field-message" id={messageId}>{hint}</p> : null}</div>;
}

export type DateRangeValue = { start?: string; end?: string };
export function DateRangeField({ label = "Période", value, onValueChange, min, max, error, required }: { label?: string; value: DateRangeValue; onValueChange: (value: DateRangeValue) => void; min?: string; max?: string; error?: string; required?: boolean }) {
  const startId = useId(); const endId = useId(); const errorId = useId(); const invalidRange = Boolean(value.start && value.end && value.end < value.start); const resolvedError = error ?? (invalidRange ? "La date de fin doit être postérieure à la date de début." : undefined);
  return <fieldset className="date-range-field" aria-describedby={resolvedError ? errorId : undefined}><legend>{label}</legend><div><div className="field"><label htmlFor={startId}>Date de début</label><Input id={startId} type="date" value={value.start ?? ""} min={min} max={value.end ?? max} required={required} invalid={Boolean(resolvedError)} onChange={(event) => onValueChange({ ...value, start: event.target.value || undefined })} /></div><div className="field"><label htmlFor={endId}>Date de fin</label><Input id={endId} type="date" value={value.end ?? ""} min={value.start ?? min} max={max} required={required} invalid={Boolean(resolvedError)} onChange={(event) => onValueChange({ ...value, end: event.target.value || undefined })} /></div></div>{resolvedError ? <p id={errorId} className="field-message error" role="alert">{resolvedError}</p> : null}</fieldset>;
}

export function TimeField({ label = "Heure", value, onValueChange, min, max, step = 300, error, required }: { label?: string; value?: string; onValueChange: (value: string) => void; min?: string; max?: string; step?: number; error?: string; required?: boolean }) {
  const id = useId(); const errorId = useId(); return <div className="field"><div className="field-label-row"><label htmlFor={id}>{label}</label></div><Input id={id} type="time" value={value ?? ""} min={min} max={max} step={step} required={required} invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} onChange={(event) => onValueChange(event.target.value)} />{error ? <p id={errorId} className="field-message error" role="alert">{error}</p> : null}</div>;
}
